In [1]:
import numpy as np

In [27]:
p_out = np.zeros((10,5))
p_out_min = [0.01,0.02,0.03,0.1,0.3]
p_out_max = [0.1,0.2,0.3,0.5,0.7]
a = np.array([1,2,3,4,6])

In [28]:
for i in range(10):
  for j in range(5):
    p_out[i,j] = p_out_max[j] + (p_out_min[j]-p_out_max[j])/9 * ((i+1)-1)

In [29]:
p_out

array([[0.1       , 0.2       , 0.3       , 0.5       , 0.7       ],
       [0.09      , 0.18      , 0.27      , 0.45555556, 0.65555556],
       [0.08      , 0.16      , 0.24      , 0.41111111, 0.61111111],
       [0.07      , 0.14      , 0.21      , 0.36666667, 0.56666667],
       [0.06      , 0.12      , 0.18      , 0.32222222, 0.52222222],
       [0.05      , 0.1       , 0.15      , 0.27777778, 0.47777778],
       [0.04      , 0.08      , 0.12      , 0.23333333, 0.43333333],
       [0.03      , 0.06      , 0.09      , 0.18888889, 0.38888889],
       [0.02      , 0.04      , 0.06      , 0.14444444, 0.34444444],
       [0.01      , 0.02      , 0.03      , 0.1       , 0.3       ]])

In [36]:
best_score = np.zeros((300,10))
best_shot = np.zeros((300,10))

In [37]:
for w in range(10):
  if(w>=9):
    best_score[0,w] = max((1-p_out[w,:])*a)
    best_shot[0,w] = a[np.argmax((1-p_out[w,:])*a,axis=0)]

In [38]:
for w in range(10):
  for b in range(1,300):
    if(b+w>=9):
      best_score[b,w] = max( (1-p_out[w,:])*(a+best_score[b-1,w]) + (p_out[w,:]*best_score[b-1,w-1] if (w>0) else 0)) 
      best_shot[b,w] = a[np.argmax( (1-p_out[w,:])*(a+best_score[b-1,w]) + (p_out[w,:]*best_score[b-1,w-1] if (w>0) else 0))]

In [39]:
best_score[299,:]

array([  9.        ,  19.11111111,  30.6111111 ,  43.89682499,
        59.56347574,  78.56305496, 102.55557234, 134.80114326,
       183.16495861, 279.55331218])

In [40]:
best_score

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   4.2       ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          3.93333333,   7.38      ],
       [  0.        ,   0.        ,   0.        , ...,   3.66666667,
          6.78740741,  10.63533333],
       ...,
       [  9.        ,  19.11111111,  30.6111111 , ..., 134.79566022,
        183.13889515, 279.48766058],
       [  9.        ,  19.11111111,  30.6111111 , ..., 134.79843857,
        183.15203045, 279.52068527],
       [  9.        ,  19.11111111,  30.6111111 , ..., 134.80114326,
        183.16495861, 279.55331218]])

In [41]:
best_shot

array([[0., 0., 0., ..., 0., 0., 6.],
       [0., 0., 0., ..., 0., 6., 4.],
       [0., 0., 0., ..., 6., 4., 4.],
       ...,
       [1., 1., 1., ..., 1., 1., 2.],
       [1., 1., 1., ..., 1., 1., 2.],
       [1., 1., 1., ..., 1., 1., 2.]])