In [6]:
import numpy as np
import re
from collections import Counter

In [7]:
f = open('speechs.txt')
dat = f.read()

In [8]:
#dat = re.sub('"'," ",dat)
#dat = re.sub("'"," ",dat)

In [9]:
dat_words = dat.split()
words = {x:dat_words.count(x) for x in dat_words}

In [10]:
i = 0
word_idx = dict()
idx_word = dict()
for word in words:
  word_idx[word] = i
  idx_word[i] = word 
  i+=1

In [11]:
word_idx['super'],idx_word[1986]

(1986, 'super')

In [12]:
print("Total unique words = ",len(words))

Total unique words =  2949


In [13]:
cnt_data = np.zeros(shape=(len(words),len(words)))     #frequency table 2d array

In [14]:
for i in range(len(dat_words)-1):
  cnt_data[word_idx[dat_words[i]]][word_idx[dat_words[i+1]]]+=1
cnt_data

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
freq_data = np.array(cnt_data)

In [16]:
for i in range(len(words)):
  if(sum(freq_data[i,:])!=0):
    freq_data[i,:] = freq_data[i,:]/sum(freq_data[i,:])

In [17]:
freq_data

array([[0.    , 1.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.0625, ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       ...,
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ]])

In [18]:
cnt_data

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
def gen_next_word(word): 
  idx = word_idx[word]
  rng = np.random.rand()
  arr = []
  for i in range(len(words)):
    arr.append((freq_data[idx,i],i))
  arr.sort()
  arr.reverse()
  cur = 0
  j = 0
  while(rng>cur+arr[j][0] and j<len(words)):
    cur += arr[j][0]
    j+=1
  if(j>len(words)):
    j-=1
  return(idx_word[arr[j][1]])

In [20]:
def freq_next_word(word):
  idx = word_idx[word]
  return(cnt_data[idx,:])

In [21]:
freq_list = freq_next_word('one').tolist()
i = 0
for j in freq_list:
  print('(',idx_word[i],j,')',end='')
  i+=1

( Maybe 0.0 )( one 0.0 )( unisex 1.0 )( avatar, 0.0 )( with 0.0 )( medium-length 0.0 )( hair? 0.0 )( :) 0.0 )( Cooking 0.0 )( & 0.0 )( #SandraBullock 0.0 )( movie 0.0 )( marathon. 0.0 )( "A 0.0 )( Time 0.0 )( to 1.0 )( Kill" 0.0 )( "YaYa 0.0 )( Sisterhood" 0.0 )( ... 0.0 )( IMO 0.0 )( is 0.0 )( of 3.0 )( the 0.0 )( most 0.0 )( beautiful 0.0 )( women 0.0 )( ever. 0.0 )( Excellent, 0.0 )( thanks! 0.0 )( omg 0.0 )( yes!!! 0.0 )( he 0.0 )( was 0.0 )( just 0.0 )( on 0.0 )( punkd 0.0 )( I 0.0 )( almost 0.0 )( died 0.0 )( Love 0.0 )( that 0.0 )( moment 0.0 )( when 0.0 )( you 0.0 )( 1st 0.0 )( discover 0.0 )( a 0.0 )( new 0.0 )( favorite 0.0 )( top 0.0 )( or 0.0 )( accessory! 0.0 )( What 0.0 )( your 0.0 )( latest 0.0 )( exciting 0.0 )( find? 0.0 )( either 0.0 )( 2 0.0 )( ever 0.0 )( get 0.0 )( chance 0.0 )( actually 0.0 )( ride 0.0 )( Mustng? 0.0 )( Would 0.0 )( love 0.0 )( have 0.0 )( chance. 0.0 )( Bout 0.0 )( go 0.0 )( see 0.0 )( my 0.0 )( ex 0.0 )( boyfriend 0.0 )( big 0.0 )( screen 0.0 )(

In [39]:
gen_next_word('one')

'too?'

In [40]:
gen_sample = []

In [43]:
nparas = np.random.randint(25,50)
for _ in range(nparas):
  nwords = int(abs(np.random.normal(25,5)))
  rng = np.random.randint(0,len(words))
  cur_word = idx_word[rng]
  print(cur_word,end=' ')
  for i in range(nwords):
    gen_sample.append(cur_word)
    cur_word = gen_next_word(cur_word)
    print(cur_word,end=' ')
  print()

based on my email: At field. It's March! You aren't the video? Talk about muscle fatigue? at #FPAC20 this time. So many students work again ever 
again for the things yourself Can anyone help :) #circasurvive at distributors for brand pages, and find 
blame on #GoodDayOregon this bottle of this bottle of you a while, but emotions make you act" Compelling matchup in life that is trending on a cocktail. thank you 
years. alright I'm so many billionaires manipulating the fall! /yd Just making sure! Home now, I love to amazon I'm just now Gingham I started with horses & rich parents 
yes, I did. The dream. In my hair and pozole before 2012? Obviously FB should think ppl when I am one lucky man Thank 
debut of 'Sushi: The first step :) I am not until I should tweet but emotions make you fall in #Alaska and Kelsey name the day; 
CM Cardenas just becuz the big thank you have even mention ! :D Yes..I did u make her find Jeff will soon 
Burleson??? Leave your best way different reasons, but we 

In [24]:
rng = np.random.randint(0,len(words))
cur_word = idx_word[rng]
print(cur_word,end=' ')
for i in range(1000):
  gen_sample.append(cur_word)
  cur_word = gen_next_word(cur_word)
  print(cur_word,end=' ')

#GOP has been enough. #juststoprightthere #Atlanta and #MKE tweeps - www.rachelmagee.com, happy they had in the game Saturday morning at revolution I'n ft. Lauderdale... Dude rocks geddy lee vocals "Put your car alignment since Saturday. I want to have one they're talking about The Clubhouse on the RBB followers Did you guys!!! That Said " DANGER , And iWas tryna open it again... Lol Police Activity (21st & #SandraBullock movie talladega nights we promise! :) lol that I Just ate The theme is in our single, Miss Me Now! time Thanks for joining all the keyboard that sounds contagious. Chicken and Noah Gordon! “Leadership is lmk if you so make whether to think you cinco de mayo So many fun and also am wasting my finger. Comedy is to address. my butterfly that's amazing and #MKE tweeps - Thank you, Holly! :) I went out to the political reporter Aman Batheja laid off Going thru pics ready? Spread the Twitter account when you right in your support! Will we do. God please explain to do women 

In [ ]:
gen_text = open('generated_text.txt','a')

In [ ]:
for word in gen_sample:
  gen_text.write(word)
  gen_text.write(' ')