In [1]:
import numpy as np
import pandas as pd

In [2]:
x_size = 5                                                        #method for making x_size*y_size array such that it contains random 10 dirt locations
y_size = 5
d = np.zeros(x_size*y_size)
for i in range(10):
  d[i] = 1  
np.random.shuffle(d)
d = d.reshape(x_size,y_size)
print(d)

[[0. 1. 1. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1.]]


In [3]:
class Agent:
  actions = ['left','right','up','down','pick-dirt']
  def __init__(self):
    self.pos = np.array([0,0])
    self.points = 0
  def action(self,observation):
    rng = np.random.randint(0,5)
    return(self.actions[rng])

In [4]:
class Environment:
  def __init__(self,x_size,y_size):
    self.d = np.zeros(x_size*y_size)
    for i in range(10):
      self.d[i] = 1
    np.random.shuffle(self.d)
    self.d = self.d.reshape(x_size,y_size)
    self.agent_pos = np.array([0,0])
    self.reward = 0
  
  def observation(self):
    return self.d

  def is_inside(self,pos):
    if(pos[0]>=0 and pos[0] < self.d.shape[0] and pos[1]>=0 and pos[1] < self.d.shape[1]):
      return 1
    else:
      return 0

  def change_state(self,action):
    if(action=='left'):
      if(self.is_inside(self.agent_pos+[-1,0])):
        self.agent_pos += [-1,0]
        self.reward = 0
      else:
        self.reward = -10
    if(action=='up'):
      if(self.is_inside(self.agent_pos+[0,1])):
        self.agent_pos += [0,1]
        self.reward = 0
      else:
        self.reward = -10
    if(action=='down'):
      if(self.is_inside(self.agent_pos+[0,-1])):
        self.agent_pos += [0,-1]
        self.reward = 0
      else:
        self.reward = -10
    if(action=='right'):
      if(self.is_inside(self.agent_pos+[1,0])):
        self.agent_pos += [1,0]  
        self.reward = 0
      else:
        self.reward = -10
    if(action=='pick-dirt'):
      if(self.d[self.agent_pos[0],self.agent_pos[1]]==1):
        self.reward = 1
        self.d[self.agent_pos[0],self.agent_pos[1]] = 0
      else:
        self.reward = -1


In [5]:
e1 = Environment(20,20)
a1 = Agent()
final_data = pd.DataFrame({});

###1)

In [6]:
for t in range(100):
  obs = e1.observation()
  act = a1.action(obs)
  loc1 = (a1.pos[0],a1.pos[1])
  state1 = e1.d[a1.pos[0],a1.pos[1]]
  e1.change_state(act)
  a1.pos = e1.agent_pos
  state2 = e1.d[a1.pos[0],a1.pos[1]]
  r = e1.reward
  a1.points += r
  dat = {'time':t+1,'state1':state1,'location1':loc1,'action':act,'state2':state2,'reward':r,'location2':(a1.pos[0],a1.pos[1])}
  print(dat)
  final_data = final_data.append(dat,ignore_index=True);

{'time': 1, 'state1': 0.0, 'location1': (0, 0), 'action': 'left', 'state2': 0.0, 'reward': -10, 'location2': (0, 0)}
{'time': 2, 'state1': 0.0, 'location1': (0, 0), 'action': 'up', 'state2': 0.0, 'reward': 0, 'location2': (0, 1)}
{'time': 3, 'state1': 0.0, 'location1': (0, 1), 'action': 'down', 'state2': 0.0, 'reward': 0, 'location2': (0, 0)}
{'time': 4, 'state1': 0.0, 'location1': (0, 0), 'action': 'right', 'state2': 0.0, 'reward': 0, 'location2': (1, 0)}
{'time': 5, 'state1': 0.0, 'location1': (1, 0), 'action': 'up', 'state2': 1.0, 'reward': 0, 'location2': (1, 1)}
{'time': 6, 'state1': 1.0, 'location1': (1, 1), 'action': 'pick-dirt', 'state2': 0.0, 'reward': 1, 'location2': (1, 1)}
{'time': 7, 'state1': 0.0, 'location1': (1, 1), 'action': 'down', 'state2': 0.0, 'reward': 0, 'location2': (1, 0)}
{'time': 8, 'state1': 0.0, 'location1': (1, 0), 'action': 'pick-dirt', 'state2': 0.0, 'reward': -1, 'location2': (1, 0)}
{'time': 9, 'state1': 0.0, 'location1': (1, 0), 'action': 'right', 'st

###2)

In [7]:
print("total reward:",a1.points,"\naverage reward:",a1.points/100)

total reward: -121 
average reward: -1.21


In [9]:
final_data.to_csv('agent_data_q2.csv',index=False,columns=['time','location1','state1','action','location2','state2','reward'])